# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

default_platform(:ios)

platform :ios do
  desc "CI - Setup Keychain"
  # Adapted from https://github.com/yukiarrr/ios-build-action/blob/master/fastlane/Fastfile
  # and https://medium.com/well-red/github-actions-fastlane-ios-1f6d43cce726
  
  lane :ci_beta do
    setup_project
    build_project
    cleanup_project
    upload_to_testflight
  end 

  private_lane :build_project do
    github_auth = Base64.strict_encode64(ENV["FASTLANE_MATCH_GITHUB_AUTH"])
    match(
      type: "appstore",
      # readonly: is_ci,
      readonly: true,
      keychain_name: "ci_keychain",
      keychain_password: "ci_keychain",
      git_basic_authorization: github_auth
    )
    update_project_provisioning(
      xcodeproj: "App.xcodeproj",
      profile: "ios-build.mobileprovision",
      target_filter: "App",
      build_configuration: "Release",
    )
    build_app(
      scheme: "App",
      configuration: "Release",
      workspace: "App.xcworkspace",
      output_name: "my-app.ipa",
    )
 end   

  private_lane :setup_project do
  # TODO - create pw and share across steps
  # keychain_password = SecureRandom.uuid
    create_keychain(
      name: "ci_keychain",
      password: "ci_keychain",
      default_keychain: true,
      unlock: true,
      timeout: 3600,
      lock_when_sleeps: false
    ) 
  end 

  private_lane :cleanup_project do
    delete_keychain(
      name: "ci_keychain"
    )
  end

  desc "Push a new beta build to TestFlight"
  lane :beta do
    build_app(workspace: "App.xcworkspace", scheme: "App")
    upload_to_testflight
  end
end
