# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

default_platform(:ios)

platform :ios do
  desc "CI - Setup Keychain"
  # Adapted from https://github.com/yukiarrr/ios-build-action/blob/master/fastlane/Fastfile
  lane :ci do
    keychain_password = SecureRandom.uuid
    create_keychain(
      name: "ios-build.keychain",
      password: 'keychain_password',
      default_keychain: true,
      unlock: true,
      timeout: 3600,
      lock_when_sleeps: false,
      require_create: true
    )
    import_certificate(
      certificate_path: "ios-build.p12",
      # certificate_password: ENV["CERTIFICATE_PASSWORD"],
      keychain_name: "ios-build.keychain",
      keychain_password: 'keychain_password',
      log_output: true
    )
    install_provisioning_profile(
      path: "ios-build.mobileprovision"
    )
    disable_automatic_code_signing
    build_app(workspace: "App.xcworkspace", scheme: "App")
    upload_to_testflight
    delete_keychain(
      name: "ios-build.keychain"
    )
  end

  desc "Push a new beta build to TestFlight"
  lane :beta do
    build_app(workspace: "App.xcworkspace", scheme: "App")
    upload_to_testflight
  end
end
